source 'https://github.com/CocoaPods/Specs.git'

target 'CloudCore_Example', :exclusive => true do
  pod "CloudCore", :path => "../"
end

target 'CloudCore_Tests', :exclusive => true do
  pod "CloudCore", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'MagicalRecord'
end
